#!/usr/bin/env python3
"""Add a single round-robin SSH alias for the Voltage Park cluster.

Replaces the original 32-entry version. Writes one Host block whose
ProxyCommand picks a random ingress IP from the K8s NodePort range
(159.26.85.33-64 by default) at connection time, so `ssh vp` lands on the
login Service via a different ingress each time without cluttering
~/.ssh/config with 32 near-identical stanzas.

Idempotent: re-running detects an existing `Host {ALIAS}` and skips.

Run:
    python3 nodes_v2.py                   # uses default user "default_non_user"
    python3 nodes_v2.py --user jsardinha  # set the cluster username
    python3 nodes_v2.py --help            # show all options

Then: ssh vp
"""

import argparse
from pathlib import Path

SSH_CONFIG = Path.home() / ".ssh" / "config"
ALIAS = "vp"
SUBNET = "159.26.85"
FIRST_OCTET = 33  # inclusive
LAST_OCTET = 64   # inclusive
PORT = 30022
KEY = "~/.ssh/voltage-park_id_ed25519"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Append a round-robin SSH alias for Voltage Park to ~/.ssh/config.",
    )
    parser.add_argument(
        "--user",
        default="default_non_user",
        help="Cluster username for the Host block (default: %(default)s).",
    )
    return parser.parse_args()


def alias_already_defined(text: str, alias: str) -> bool:
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        head, _, rest = stripped.partition(" ")
        if head.lower() == "host" and alias in rest.split():
            return True
    return False


def main() -> None:
    assert FIRST_OCTET < LAST_OCTET, "FIRST_OCTET must be < LAST_OCTET"
    span = LAST_OCTET - FIRST_OCTET + 1
    args = parse_args()

    # %% is a literal % in ssh_config (% is reserved for tokens like %h, %p).
    # The shell that bash -c invokes ultimately sees `RANDOM % {span}`.
    block = (
        f"\n\n#### Voltage Park SSH Configs ###\n"
        f"# autogenerated, do not touch\n"
        f"# usage: ssh {ALIAS}\n"
        f"Host {ALIAS}\n"
        f"  ProxyCommand bash -c 'IP={SUBNET}.$(({FIRST_OCTET} + RANDOM %% {span})); exec nc $IP {PORT}'\n"
        f"  User {args.user}\n"
        f"  IdentityFile {KEY}\n"
        f"  ForwardAgent yes\n"
        f"  HostKeyAlias voltage-park\n"
        f"  StrictHostKeyChecking accept-new\n"
        f"#################################\n"
    )

    existing = SSH_CONFIG.read_text() if SSH_CONFIG.exists() else ""
    if alias_already_defined(existing, ALIAS):
        print(f"'Host {ALIAS}' is already in {SSH_CONFIG}; nothing to do.")
        return

    with SSH_CONFIG.open("a") as f:
        f.write(block)

    print(f"Added 'Host {ALIAS}' to {SSH_CONFIG}:")
    print(block.rstrip())
    print(f"\nTry it with: ssh -v {ALIAS}")


if __name__ == "__main__":
    main()
